import type { Document, ExtractedField, BusinessCheck, FieldGroupMeta } from "@/lib/types"
import { FIELD_COLORS } from "@/lib/constants"

// ── Documents ────────────────────────────────────────────────────────────────
export const mockDocuments: Document[] = [
  {
    id: "1",
    name: "191105_AFSOC_Parachute_Mishap_AIB_Report.pdf",
    status: "new",
    pages: 52,
    tags: ["AIB", "AFSOC"],
    errorRate: 12,
    lastEdited: "2026-02-10T14:32:00Z",
    isFlagged: false,
  },
  {
    id: "2",
    name: "F16_Mishap_Report_2024.pdf",
    status: "annotated",
    pages: 34,
    tags: ["F-16", "Flight"],
    errorRate: 3,
    lastEdited: "2026-02-08T09:15:00Z",
    isFlagged: true,
  },
  {
    id: "3",
    name: "CV22_Investigation_2023.pdf",
    status: "in-progress",
    pages: 28,
    tags: ["CV-22", "Investigation"],
    errorRate: 28,
    lastEdited: "2026-02-11T16:45:00Z",
    isFlagged: false,
  },
  {
    id: "4",
    name: "B1B_Lancer_Ground_Mishap_AIB_2022.pdf",
    status: "annotated",
    pages: 41,
    tags: ["B-1B", "AIB", "Ground"],
    errorRate: 5,
    lastEdited: "2026-01-28T11:00:00Z",
    isFlagged: false,
  },
  {
    id: "5",
    name: "UH60_BlackHawk_Engine_Failure_2023.pdf",
    status: "annotated-editing",
    pages: 19,
    tags: ["UH-60", "Class B"],
    errorRate: 18,
    lastEdited: "2026-02-25T08:20:00Z",
    isFlagged: true,
  },
  {
    id: "6",
    name: "MQ9_Reaper_Lost_Link_Incident_2024.pdf",
    status: "new",
    pages: 23,
    tags: ["MQ-9", "UAS", "AFSOC"],
    errorRate: 31,
    lastEdited: "2026-02-18T15:10:00Z",
    isFlagged: false,
  },
  {
    id: "7",
    name: "C17_Globemaster_Cargo_Shift_Report.pdf",
    status: "in-progress",
    pages: 36,
    tags: ["C-17", "AMC"],
    errorRate: 9,
    lastEdited: "2026-02-27T13:55:00Z",
    isFlagged: false,
  },
  {
    id: "8",
    name: "A10_Thunderbolt_Bird_Strike_Class_C.pdf",
    status: "annotated",
    pages: 14,
    tags: ["A-10", "Class C"],
    errorRate: 0,
    lastEdited: "2026-01-15T10:30:00Z",
    isFlagged: false,
  },
  {
    id: "9",
    name: "AH64_Apache_Hard_Landing_Investigation.pdf",
    status: "new",
    pages: 47,
    tags: ["AH-64", "Army", "Class A"],
    errorRate: 22,
    lastEdited: "2026-02-05T09:00:00Z",
    isFlagged: false,
  },
  {
    id: "10",
    name: "F35A_Canopy_Depart_Safety_Review_2025.pdf",
    status: "in-progress",
    pages: 61,
    tags: ["F-35", "Flight", "USAF"],
    errorRate: 14,
    lastEdited: "2026-02-28T17:30:00Z",
    isFlagged: true,
  },
  {
    id: "11",
    name: "V22_Osprey_FARP_Ops_Safety_Board.pdf",
    status: "annotated",
    pages: 29,
    tags: ["V-22", "SOCOM"],
    errorRate: 7,
    lastEdited: "2026-01-31T14:00:00Z",
    isFlagged: false,
  },
  {
    id: "12",
    name: "KC135_Stratotanker_Fuel_Leak_2024.pdf",
    status: "new",
    pages: 18,
    tags: ["KC-135", "AMC", "Ground"],
    errorRate: 0,
    lastEdited: "2026-03-01T07:45:00Z",
    isFlagged: false,
  },
]

// ── Extracted Fields ─────────────────────────────────────────────────────────
export const mockExtractedFields: ExtractedField[] = [
  // ── Mishap Overview ──────────────────────────────────────────────────────
  {
    id: "mishap-date",
    group: "Mishap Overview",
    name: "Mishap Date",
    dataType: "date",
    extractionType: "exact",
    isInferred: false,
    value: "5 November 2019",
    reference: { text: "5 November 2019", page: 1, position: { x: 120, y: 280 } },
    prediction: "5 November 2019",
    initialPrediction: "5 November 2019",
    initialReference: { text: "5 November 2019", page: 1, position: { x: 120, y: 280 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[0],
    instructions:
      "Extract the exact date when the mishap/incident occurred. Look for explicit date mentions in the report header or summary sections.",
    fieldScore: "great",
    extractedInDocument: true,
  },
  {
    id: "mishap-location",
    group: "Mishap Overview",
    name: "Location",
    dataType: "string",
    extractionType: "exact",
    isInferred: false,
    value: "Hurlburt Field, FL",
    reference: { text: "Hurlburt Field, FL", page: 1, position: { x: 120, y: 320 } },
    prediction: "Hurlburt Field, FL",
    initialPrediction: "Hurlburt Field, FL",
    initialReference: { text: "Hurlburt Field, FL", page: 1, position: { x: 120, y: 320 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[1],
    instructions:
      "Extract the geographic location where the incident took place. Include base name, city, and state if available.",
    fieldScore: "great",
    extractedInDocument: true,
  },
  {
    id: "mishap-class",
    group: "Mishap Overview",
    name: "Mishap Class",
    dataType: "string",
    extractionType: "inferred",
    isInferred: true,
    value: "Class A - Fatal",
    reference: { text: "sustained fatal injuries", page: 1, position: { x: 200, y: 360 } },
    prediction: "Class A - Fatal",
    initialPrediction: "Class A - Fatal",
    initialReference: { text: "sustained fatal injuries", page: 1, position: { x: 200, y: 360 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[2],
    validationStatus: "pass",
    fieldScore: "good",
    extractedInDocument: true,
    instructions:
      "Determine the mishap classification based on severity. Class A involves fatalities or $2.5M+ damage, Class B involves permanent disability or $600K-$2.5M damage, Class C involves lost workdays or $60K-$600K damage.",
  },
  {
    id: "aircraft-type",
    group: "Mishap Overview",
    name: "Aircraft Type",
    dataType: "string",
    isInferred: false,
    value: "MC-130H",
    reference: { text: "MC-130H", page: 1, position: { x: 150, y: 180 } },
    prediction: "MC-130H",
    initialPrediction: "MC-130H",
    initialReference: { text: "MC-130H", page: 1, position: { x: 150, y: 180 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[3],
    fieldScore: "great",
    extractedInDocument: true,
  },
  {
    id: "tail-number",
    group: "Mishap Overview",
    name: "Tail Number",
    dataType: "string",
    isInferred: false,
    value: "88-0194",
    reference: { text: "88-0194", page: 1, position: { x: 220, y: 180 } },
    prediction: "88-0194",
    initialPrediction: "88-0194",
    initialReference: { text: "88-0194", page: 1, position: { x: 220, y: 180 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[4],
    fieldScore: "good",
    extractedInDocument: true,
  },
  {
    id: "mission-type",
    group: "Mishap Overview",
    name: "Mission Type",
    dataType: "string",
    isInferred: false,
    value: "Special Tactics Parachute Training",
    reference: { text: "Special Tactics (ST) Rodeo competition", page: 1, position: { x: 180, y: 340 } },
    prediction: "Special Tactics Parachute Training",
    initialPrediction: "Special Tactics Parachute Training",
    initialReference: { text: "Special Tactics (ST) Rodeo competition", page: 1, position: { x: 180, y: 340 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[5],
    fieldScore: "moderate",
    extractedInDocument: true,
  },

  // ── Human Factors – Instance #1: Mishap Jumpmaster ──────────────────────
  {
    id: "hf1-crew-role",
    group: "Human Factors",
    subGroup: "#1",
    name: "Crew Role",
    dataType: "string",
    isInferred: false,
    value: "Mishap Jumpmaster (MJM)",
    reference: { text: "Mishap Jumpmaster (MJM)", page: 1, position: { x: 180, y: 360 } },
    prediction: "Mishap Jumpmaster (MJM)",
    initialPrediction: "Mishap Jumpmaster (MJM)",
    initialReference: { text: "Mishap Jumpmaster (MJM)", page: 1, position: { x: 180, y: 360 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[6],
    fieldScore: "good",
    extractedInDocument: true,
  },
  {
    id: "hf1-experience",
    group: "Human Factors",
    subGroup: "#1",
    name: "Experience Indicator",
    dataType: "string",
    isInferred: true,
    value: "Experienced - 23d Special Tactics Squadron",
    reference: { text: "23d Special Tactics Squadron", page: 1, position: { x: 180, y: 365 } },
    prediction: "Experienced - 23d Special Tactics Squadron",
    initialPrediction: "Experienced - 23d Special Tactics Squadron",
    initialReference: { text: "23d Special Tactics Squadron", page: 1, position: { x: 180, y: 365 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[7],
    validationStatus: "fail",
    fieldScore: "bad",
    extractedInDocument: true,
  },
  {
    id: "hf1-factor",
    group: "Human Factors",
    subGroup: "#1",
    name: "Human Factor Identified",
    dataType: "string",
    isInferred: false,
    value: "Procedural knowledge deficit on T-11R Reserve",
    reference: {
      text: "procedural knowledge on the T-11R Reserve inserts and side tuck-tabs",
      page: 2,
      position: { x: 150, y: 520 },
    },
    prediction: "Procedural knowledge deficit on T-11R Reserve",
    initialPrediction: "Procedural knowledge deficit on T-11R Reserve",
    initialReference: {
      text: "procedural knowledge on the T-11R Reserve inserts and side tuck-tabs",
      page: 2,
      position: { x: 150, y: 520 },
    },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[8],
    fieldScore: "moderate",
    extractedInDocument: true,
  },

  // ── Human Factors – Instance #2: Training/Standards Issues ──────────────
  {
    id: "hf2-crew-role",
    group: "Human Factors",
    subGroup: "#2",
    name: "Crew Role",
    dataType: "string",
    isInferred: true,
    value: "Training & Standards Leadership",
    reference: { text: "Training and Standards/Evaluations program management", page: 2, position: { x: 150, y: 555 } },
    prediction: "Training & Standards Leadership",
    initialPrediction: "Training & Standards Leadership",
    initialReference: {
      text: "Training and Standards/Evaluations program management",
      page: 2,
      position: { x: 150, y: 555 },
    },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[6],
    validationStatus: "pass",
    fieldScore: "good",
    extractedInDocument: true,
  },
  {
    id: "hf2-experience",
    group: "Human Factors",
    subGroup: "#2",
    name: "Experience Indicator",
    dataType: "string",
    isInferred: true,
    value: "Organizational Level",
    reference: { text: "organizational", page: 2, position: { x: 150, y: 555 } },
    prediction: "Organizational Level",
    initialPrediction: "Organizational Level",
    initialReference: { text: "organizational", page: 2, position: { x: 150, y: 555 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[7],
    fieldScore: "moderate",
    extractedInDocument: false,
  },
  {
    id: "hf2-factor",
    group: "Human Factors",
    subGroup: "#2",
    name: "Human Factor Identified",
    dataType: "string",
    isInferred: false,
    value: "Inadequate training program management",
    reference: {
      text: "lacked investment in time, intellect and resources for Training and Standards/Evaluations program management",
      page: 2,
      position: { x: 150, y: 555 },
    },
    prediction: "Inadequate training program management",
    initialPrediction: "Inadequate training program management",
    initialReference: {
      text: "lacked investment in time, intellect and resources for Training and Standards/Evaluations program management",
      page: 2,
      position: { x: 150, y: 555 },
    },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[8],
    fieldScore: "bad",
    extractedInDocument: true,
  },

  // ── Human Factors – Instance #3: Organizational Leadership ──────────────
  {
    id: "hf3-crew-role",
    group: "Human Factors",
    subGroup: "#3",
    name: "Crew Role",
    dataType: "string",
    isInferred: true,
    value: "Organizational Leadership",
    reference: { text: "Inadequate organizational leadership", page: 2, position: { x: 150, y: 570 } },
    prediction: "Organizational Leadership",
    initialPrediction: "Organizational Leadership",
    initialReference: { text: "Inadequate organizational leadership", page: 2, position: { x: 150, y: 570 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[6],
    fieldScore: "moderate",
    extractedInDocument: false,
  },
  {
    id: "hf3-experience",
    group: "Human Factors",
    subGroup: "#3",
    name: "Experience Indicator",
    dataType: "string",
    isInferred: true,
    value: "Command Level",
    reference: { text: "command oversight", page: 2, position: { x: 150, y: 570 } },
    prediction: "Command Level",
    initialPrediction: "Command Level",
    initialReference: { text: "command oversight", page: 2, position: { x: 150, y: 570 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[7],
    fieldScore: "bad",
    extractedInDocument: false,
  },
  {
    id: "hf3-factor",
    group: "Human Factors",
    subGroup: "#3",
    name: "Human Factor Identified",
    dataType: "string",
    isInferred: false,
    value: "Insufficient command oversight",
    reference: {
      text: "Inadequate organizational leadership led to insufficient command oversight of this event",
      page: 2,
      position: { x: 150, y: 570 },
    },
    prediction: "Insufficient command oversight",
    initialPrediction: "Insufficient command oversight",
    initialReference: {
      text: "Inadequate organizational leadership led to insufficient command oversight of this event",
      page: 2,
      position: { x: 150, y: 570 },
    },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[8],
    fieldScore: "moderate",
    extractedInDocument: true,
  },

  // ── Findings ─────────────────────────────────────────────────────────────
  {
    id: "primary-cause",
    group: "Findings",
    name: "Primary Cause",
    dataType: "string",
    isInferred: false,
    value: "Incorrectly configured T-11R reserve parachute",
    reference: {
      text: "incorrectly configured T-11R reserve parachute as a direct result of jumpmaster procedural knowledge",
      page: 2,
      position: { x: 150, y: 510 },
    },
    prediction: "Incorrectly configured T-11R reserve parachute",
    initialPrediction: "Incorrectly configured T-11R reserve parachute",
    initialReference: {
      text: "incorrectly configured T-11R reserve parachute as a direct result of jumpmaster procedural knowledge",
      page: 2,
      position: { x: 150, y: 510 },
    },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[3],
    fieldScore: "good",
    extractedInDocument: true,
  },
  {
    id: "contributing-factor-1",
    group: "Findings",
    name: "Contributing Factor 1",
    dataType: "string",
    isInferred: false,
    value: "TO process failed to deliver information effectively",
    reference: {
      text: "The TO process failed to deliver information effectively",
      page: 2,
      position: { x: 150, y: 540 },
    },
    prediction: "TO process failed to deliver information effectively",
    initialPrediction: "TO process failed to deliver information effectively",
    initialReference: {
      text: "The TO process failed to deliver information effectively",
      page: 2,
      position: { x: 150, y: 540 },
    },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[4],
    fieldScore: "bad",
    extractedInDocument: true,
  },

  // ── Financial Data (Business Check demonstration) ────────────────────────
  {
    id: "account-capital-earnings",
    group: "Financial Data",
    name: "Account Capital Earnings",
    dataType: "number",
    isInferred: false,
    value: "$125,000.00",
    reference: { text: "Account Capital Earnings: $125,000.00", page: 3, position: { x: 150, y: 120 } },
    prediction: "$125,000.00",
    initialPrediction: "$125,000.00",
    initialReference: { text: "Account Capital Earnings: $125,000.00", page: 3, position: { x: 150, y: 120 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[9],
    validationStatus: "fail",
    fieldScore: "moderate",
    extractedInDocument: true,
  },
  {
    id: "ytd-roi-1",
    group: "Financial Data",
    subGroup: "Q1",
    name: "YTD ROI",
    dataType: "number",
    isInferred: false,
    value: "$32,500.00",
    reference: { text: "Q1 ROI: $32,500.00", page: 3, position: { x: 150, y: 180 } },
    prediction: "$32,500.00",
    initialPrediction: "$32,500.00",
    initialReference: { text: "Q1 ROI: $32,500.00", page: 3, position: { x: 150, y: 180 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[10],
    validationStatus: "fail",
    fieldScore: "good",
    extractedInDocument: true,
  },
  {
    id: "ytd-roi-2",
    group: "Financial Data",
    subGroup: "Q2",
    name: "YTD ROI",
    dataType: "number",
    isInferred: false,
    value: "$28,750.00",
    reference: { text: "Q2 ROI: $28,750.00", page: 3, position: { x: 150, y: 200 } },
    prediction: "$28,750.00",
    initialPrediction: "$28,750.00",
    initialReference: { text: "Q2 ROI: $28,750.00", page: 3, position: { x: 150, y: 200 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[10],
    validationStatus: "fail",
    fieldScore: "great",
    extractedInDocument: true,
  },
  {
    id: "ytd-roi-3",
    group: "Financial Data",
    subGroup: "Q3",
    name: "YTD ROI",
    dataType: "number",
    isInferred: false,
    value: "$41,200.00",
    reference: { text: "Q3 ROI: $41,200.00", page: 3, position: { x: 150, y: 220 } },
    prediction: "$41,200.00",
    initialPrediction: "$41,200.00",
    initialReference: { text: "Q3 ROI: $41,200.00", page: 3, position: { x: 150, y: 220 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[10],
    validationStatus: "fail",
    fieldScore: "good",
    extractedInDocument: true,
  },
  {
    id: "earning-gains",
    group: "Financial Data",
    name: "Earning Gains",
    dataType: "number",
    isInferred: false,
    value: "$18,500.00",
    reference: { text: "Total Earning Gains: $18,500.00", page: 3, position: { x: 150, y: 280 } },
    prediction: "$18,500.00",
    initialPrediction: "$18,500.00",
    initialReference: { text: "Total Earning Gains: $18,500.00", page: 3, position: { x: 150, y: 280 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[11],
    validationStatus: "fail",
    fieldScore: "moderate",
    extractedInDocument: true,
  },
  {
    id: "tax-liabilities",
    group: "Financial Data",
    name: "Tax Liabilities",
    dataType: "number",
    isInferred: false,
    value: "$15,450.00",
    reference: { text: "Tax Liabilities: $15,450.00", page: 3, position: { x: 150, y: 320 } },
    prediction: "$15,450.00",
    initialPrediction: "$15,450.00",
    initialReference: { text: "Tax Liabilities: $15,450.00", page: 3, position: { x: 150, y: 320 } },
    isModified: false,
    isAnnotated: false,
    color: FIELD_COLORS[0],
    validationStatus: "fail",
    fieldScore: "great",
    extractedInDocument: true,
  },
]

// ── Business Checks ──────────────────────────────────────────────────────────
export const mockBusinessChecks: BusinessCheck[] = [
  {
    id: "account-capital-validation",
    name: "Account Capital Earnings Validation",
    expression: "Account Capital Earnings = SUM(YTD ROI) + Earning Gains − Tax Liabilities",
    inputFields: [
      {
        fieldId: "account-capital-earnings",
        fieldName: "Account Capital Earnings",
        isMultiOccurrence: false,
        values: [
          {
            value: 125000,
            reference: { text: "Account Capital Earnings: $125,000.00", page: 3, position: { x: 150, y: 120 } },
          },
        ],
      },
      {
        fieldId: "ytd-roi",
        fieldName: "YTD ROI",
        isMultiOccurrence: true,
        aggregationType: "SUM",
        values: [
          { value: 32500, instanceLabel: "Q1", reference: { text: "Q1 ROI: $32,500.00", page: 3, position: { x: 150, y: 180 } } },
          { value: 28750, instanceLabel: "Q2", reference: { text: "Q2 ROI: $28,750.00", page: 3, position: { x: 150, y: 200 } } },
          { value: 41200, instanceLabel: "Q3", reference: { text: "Q3 ROI: $41,200.00", page: 3, position: { x: 150, y: 220 } } },
        ],
        aggregatedValue: 102450,
      },
      {
        fieldId: "earning-gains",
        fieldName: "Earning Gains",
        isMultiOccurrence: false,
        values: [
          { value: 18500, reference: { text: "Total Earning Gains: $18,500.00", page: 3, position: { x: 150, y: 280 } } },
        ],
      },
      {
        fieldId: "tax-liabilities",
        fieldName: "Tax Liabilities",
        isMultiOccurrence: false,
        values: [
          { value: 15450, reference: { text: "Tax Liabilities: $15,450.00", page: 3, position: { x: 150, y: 320 } } },
        ],
      },
    ],
    // SUM(YTD ROI) + Earning Gains - Tax Liabilities = 102450 + 18500 - 15450 = 105500
    calculatedResult: 105500,
    expectedValue: 125000,
    status: "fail",
    description:
      "Validates that the Account Capital Earnings matches the sum of YTD ROI plus Earning Gains minus Tax Liabilities",
  },
  {
    id: "mishap-class-validation",
    name: "Mishap Classification Validation",
    expression: "Mishap Class = 'Class A' when Fatal Injuries Reported",
    inputFields: [
      {
        fieldId: "mishap-class",
        fieldName: "Mishap Class",
        isMultiOccurrence: false,
        values: [
          {
            value: "Class A - Fatal",
            reference: { text: "sustained fatal injuries", page: 1, position: { x: 200, y: 360 } },
          },
        ],
      },
    ],
    calculatedResult: 1,
    expectedValue: 1,
    status: "pass",
    description: "Validates that mishap classification is consistent with injury severity",
  },
]

// ── Group Metadata ────────────────────────────────────────────────────────────
export const initialGroupMeta: Record<string, FieldGroupMeta> = {
  "Mishap Overview": {
    name: "Mishap Overview",
    instructions:
      "Extract key summary information about the mishap incident including date, location, classification, and personnel involved.",
    fieldCount: 5,
  },
  "Human Factors": {
    name: "Human Factors",
    instructions:
      "Identify and extract human factors that contributed to the incident. Include crew experience, training status, fatigue levels, and any human errors or decision-making issues.",
    fieldCount: 4,
  },
  "Equipment & Maintenance": {
    name: "Equipment & Maintenance",
    instructions:
      "Extract information about the equipment involved, its maintenance history, any malfunctions or failures, and inspection records.",
    fieldCount: 3,
  },
}
